apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: fast_rsm
  annotations:
    workflows.argoproj.io/title: fast_rsm
    workflows.argoproj.io/description: |
      utility which takes in a experimental setup file and a scan number, then performs recirpocal space mapping and saves the results to an outpath.
    workflows.diamond.ac.uk/parameter-schema: |
      {{- .Files.Get "schema/fast_rsm_Schema.json" | nindent 6 }}
    workflows.diamond.ac.uk/ui-schema: |
      {{- .Files.Get "schema/fast_rsm_UISchema.json" | nindent 6 }}
spec:
  entrypoint: ????
  arguments:
    parameters:
    - name: visitdir
      valueFrom:
        configMapKeyRef:
          name: sessionspaces
          key: data_directory
    - name: exp_setup
      value: /dls/science/groups/das/ExampleData/i07/fast_rsm_example_data/setups/si30563_exp.py
    - name: scan_number
      value: 432196

???===========???
volumeClaimTemplates:
- metadata:
    name: tmp
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    storageClassName: netapp
???===========???

templates:
  - name: fast-rsm-mount-files
    script:
      image: ????fast-rsm image path
      command: [bash]
      source: |
        echo '{{ .Files.Get "notebooks/scriptable_processing.ipynb" | b64enc }}' | base64 -d > /tmp/notebook.ipynb
      volumeMounts:
      - name: tmp
        mountPath: /tmp
  - name: fast-rsm-notebook
    inputs:
      parameters:
      - name: exp_setup
        value: "{{`{{ workflow.parameters.exp_setup }}`}}"
      - name: scan_number
        value: "{{`{{ workflow.parameters.scan_number }}`}}"
    script:
      image: ????fast-rsm image path
      env:
      - name: HOME
        value: /tmp
      command: [bash]
      source: |
        python -m papermill /tmp/notebook.ipynb /tmp/notebook-parametrized.ipynb \
          -p inpath "{{`{{ workflow.parameters.visitdir }}`}}/scan/i14-{{`{{ inputs.parameters.singleFirst }}`}}.nxs" \
          -p process_configfile /tmp/config.yaml \
          -p outpath "{{`{{ inputs.parameters.outputFolder }}`}}/i14-{{`{{ inputs.parameters.singleFirst }}`}}_dpc-phase.nxs" \
          -p auto_processing False
        python -m jupyter nbconvert /tmp/notebook-parametrized.ipynb --to notebook --execute --allow-errors --output fast-rsm-notebook --output-dir "{{`{{ inputs.parameters.outputFolder }}`}}"
        python -m jupyter nbconvert "{{`{{ inputs.parameters.outputFolder }}`}}/dpc-notebook.ipynb" --to html --no-input --output dpc-output --output-dir "{{`{{ inputs.parameters.outputFolder }}`}}"
      
